# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Matti
                                 A QGIS plugin
 A plugin to estimate soybean maturity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-20
        copyright            : (C) 2024 by Nathaniel Burner
        email                : nburner@uga.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Matti class from file Matti.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .matti import Matti
    return Matti(iface)
